---
engines:
  checkstyle:
    enabled: true
    channel: "beta"
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - java
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  radon:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.java"
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- src/main/webapp/WEB-INF/js/backbone.localstorage/
- src/main/webapp/WEB-INF/js/backbone/
- src/main/webapp/WEB-INF/js/bootstrap/
- src/main/webapp/WEB-INF/js/cookie/
- src/main/webapp/WEB-INF/js/interact/
- src/main/webapp/WEB-INF/js/jquery/dist/
- src/main/webapp/WEB-INF/js/src-noconflict/
- src/main/webapp/WEB-INF/js/underscore/
- src/main/webapp/WEB-INF/js/w2ui/
- src/main/webapp/WEB-INF/js/wysiwyg/
- src/main/webapp/WEB-INF/css/bootstrap/
- src/main/webapp/WEB-INF/css/dragula/
- src/main/webapp/WEB-INF/css/w2ui/
